### ISSUE TITLE
Feature: user-can-browse-highest-rated-anime

### ISSUE THREAD

**Issue by JoshuaBeh** [JoshuaBeh/anime-list#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can browse highest rated anime.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can browse the highest rated anime in groups of 10, and see the next/previous 10 by clicking an arrow.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![mobile feature 1](https://user-images.githubusercontent.com/113414352/211395180-01fc80cb-6382-43dc-bddc-cd0c6093781d.png)
![desktop feature 1](https://user-images.githubusercontent.com/113414352/211395265-e912b724-18f7-4b71-8976-c20a7177b576.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Import font-awesome for star icon
- [x] Create a layout for mobile and desktop
- [x] Render a list of the 10 highest anime in the DOM (Title of each anime is an anchor tag).
- [x] Add arrows that increase/decrease the 'get request's URL' by 10 and recall the render function.
- [x] Make 'Anime' return the user to the original top 10.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
