### ISSUE TITLE
Feature: user-can-search-for-any-anime

### ISSUE THREAD

**Issue by JoshuaBeh** [JoshuaBeh/anime-list#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for any anime.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can search for any anime they wish and will be shown all the versions of that anime.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![feature 2 search-bar](https://user-images.githubusercontent.com/113414352/211398101-3dd40e35-8d18-4d7a-ab4d-7dcf2084e4c2.png)
![feature 2 results](https://user-images.githubusercontent.com/113414352/211398232-646b83ad-83f1-4060-8206-63a926dfe97a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a modal for the search bar
- [x] Make the search anchor open the modal
- [x] Set up view-swapping
- [x] Create a function that takes the user's input (search) and adds it to the get request's URL
- [x] Create a function that renders the search result in the DOM and swaps users view
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
