### ISSUE TITLE
Feature: user-can-view-details-of-a-single-anime

### ISSUE THREAD

**Issue by JoshuaBeh** [JoshuaBeh/anime-list#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

'User can view details of a single anime'
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

'When the user clicks on one of the show's versions, it will show all of the important details about that version of the show.'
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![feature 3](https://user-images.githubusercontent.com/113414352/211399052-c4bb7e08-63fb-448c-8e94-adedcd56a2ca.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a new view for the details of the user-selected anime
- [x] Make the images or names on the list of searched anime link to the new view
- [x] Create an array/object to store the data
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
