### ISSUE TITLE
Feature: user-can-add-anime-to-their-watchlist

### ISSUE THREAD

**Issue by JoshuaBeh** [JoshuaBeh/anime-list#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add anime to their watchlist.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to click the add button and the show will be added to their list.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![feature 4](https://user-images.githubusercontent.com/113414352/211400144-eec63297-7f68-4805-b268-18aa550fc214.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Set up the user's local storage
- [x] Make the add button store the necessary data in local storage
- [x] If the anime is in the user's local storage, change the button to 'In List' and on hover 'remove'
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
