### ISSUE TITLE
Feature: user-can-view-their-watchlist

### ISSUE THREAD

**Issue by JoshuaBeh** [JoshuaBeh/anime-list#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their watchlist.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks on the list anchor, they will be shown their watch list, which can be edited/deleted, and hopefully
sorted by score.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![feature 5 mobile](https://user-images.githubusercontent.com/113414352/211400822-fa986f1f-395b-4f5a-8e24-5b3f97b38ad1.png)
![image](https://user-images.githubusercontent.com/113414352/212142359-0b8dcce0-1f66-487a-bf83-c94c138128e8.png)
![feature 5 desktop](https://user-images.githubusercontent.com/113414352/211400831-7b5aba6a-702c-49d3-b4e2-e0d68ddb8b9d.png)
![image](https://user-images.githubusercontent.com/113414352/212142287-6c74af66-6c52-4d4a-8629-8029bf79d288.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a new view for the anime list
- [x] Take the data from the user's local storage and append it to the list
- [x] Create a modal for the anime list
- [x] When the user clicks on a list item, open the modal
- [x] When the user clicks save, update the user's local storage and replace the old list with the new one
- [x] When the user clicks delete, remove that item and replace the old list with the new one
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
