### ISSUE TITLE
Feature: user-can-create-a-favorite-characters-list

### ISSUE THREAD

**Issue by JoshuaBeh** [JoshuaBeh/anime-list#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a favorite characters list.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks the characters button on the anime they are looking at, it will show them all of the characters in that anime.
When they click on one of the characters, it will add/remove it to/from their list. In their characters list, the user can remove characters.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![feature 6](https://user-images.githubusercontent.com/113414352/211402075-9750b2e3-cff0-43d0-810a-526eec2208f3.png)
![feature 6 mobile](https://user-images.githubusercontent.com/113414352/211402079-5b594ca2-7444-41e3-a93c-716bcc1158b6.png)
![image](https://user-images.githubusercontent.com/113414352/212410072-2b128cd5-a99a-4196-9f13-0e4604d2305c.png)
![image](https://user-images.githubusercontent.com/113414352/212409986-d601c57d-6d60-49bf-b7b4-0a45646d568c.png)
![image](https://user-images.githubusercontent.com/113414352/212410122-a61aa2a8-fd58-414a-9e01-9eadb14d1525.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a new view for the Character list of the selected anime
- [x] Render the characters of the selected anime in the DOM when the characters button is clicked
- [x] When one of the characters images/names are clicked, it adds the character's information to local storage and swaps views to the **Yet to be created user's character list**
- [x] Create a new view for the user's character list
- [x] Render the user's characters from local storage into the DOM
- [x] Create a modal for the user's character list
- [x] When the user clicks on one of characters, the modal opens
- [x] The modal will either close or remove the selected character
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
